from django.urls import path
from .views import (
    Checkout,
    MarketFeedView,
    MyOrdersView,
    OrderStatusView,
    OrdersView,
    ProductView,
    ReviewList,
    ReviewView,
    UserIDView,
    ProductListView,
    ProductDetailView,
    AddToCartView,
    OrderDetailView,
    OrderQuantityUpdateView,
    PaymentView,
    AddCouponView,
    CountryListView,
    AddressListView,
    AddressCreateView,
    AddressUpdateView,
    AddressDeleteView,
    OrderItemDeleteView,
    PaymentListView,
    BankView,
    CreditcardView,
    UserProdctsView,
)

app_name = "product"

urlpatterns = [
    path("user-id/", UserIDView.as_view(), name="user-id"),
    path("credit-card/", CreditcardView.as_view(), name="credit-card"),
    path("productfeed/<str:category>/", MarketFeedView.as_view(), name="marketfeed"),
    path("bank/", BankView.as_view(), name="bank"),
    path("countries/", CountryListView.as_view(), name="country-list"),
    path("addresses/", AddressListView.as_view(), name="address-list"),
    path("addresses/create/", AddressCreateView.as_view(), name="address-create"),
    path("addresses/<pk>/update/", AddressUpdateView.as_view(), name="address-update"),
    path("addresses/<pk>/delete/", AddressDeleteView.as_view(), name="address-delete"),
    path("products/create/", ProductView.as_view(), name="product-create"),
    path("products/delete/<int:pk>/", ProductView.as_view(), name="product-delete"),
    path("products/update/<int:pk>/", ProductView.as_view(), name="product-update"),
    path("products/user-products/", UserProdctsView.as_view(), name="product-list"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("products/<pk>/", ProductDetailView.as_view(), name="product-detail"),
    path("add-to-cart/<slug>/", AddToCartView.as_view(), name="add-to-cart"),
    path("order-summary/", OrderDetailView.as_view(), name="order-summary"),
    path("order-status/", OrderStatusView.as_view(), name="order-status"),
    path("checkout/", Checkout.as_view(), name="checkout"),
    path("add-coupon/", AddCouponView.as_view(), name="add-coupon"),
    path("orders/get_orders/", OrdersView.as_view()),
    path("orders/get_my_orders/", MyOrdersView.as_view()),
    path(
        "order-items/<pk>/delete/",
        OrderItemDeleteView.as_view(),
        name="order-item-delete",
    ),
    path(
        "order-item/update-quantity/",
        OrderQuantityUpdateView.as_view(),
        name="order-item-update-quantity",
    ),
    path("payments/", PaymentListView.as_view(), name="payment-list"),
    path("review/create/", ReviewView.as_view(), name="create-review"),
    path('reviews/<int:pk>/', ReviewList.as_view(), name='review-list'),
]
